"""add patient and doctor models.

Revision details for database migration.

Revision ID: 01eb609ef020
Revises: 33c265c73141
Create Date: 2026-01-27 21:42:22.515061
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "01eb609ef020"
down_revision: str | None = "33c265c73141"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("specialty_id", sa.Uuid(), nullable=False),
        sa.Column(
            "license_number",
            AutoString(length=50),
            nullable=False,
        ),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column(
            "qualifications",
            AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("bio", AutoString(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_doctors_id"), "doctors", ["id"], unique=False)
    op.create_index(
        op.f("ix_doctors_is_active"), "doctors", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_doctors_license_number"), "doctors", ["license_number"], unique=True
    )
    op.create_index(
        op.f("ix_doctors_specialty_id"), "doctors", ["specialty_id"], unique=False
    )
    op.create_index(op.f("ix_doctors_user_id"), "doctors", ["user_id"], unique=True)
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document", AutoString(length=20), nullable=False),
        sa.Column("phone", AutoString(length=20), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_document"), "patients", ["document"], unique=True)
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    op.create_index(op.f("ix_patients_user_id"), "patients", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_user_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_document"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_doctors_user_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_specialty_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_license_number"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_is_active"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_id"), table_name="doctors")
    op.drop_table("doctors")
    # ### end Alembic commands ###
