"""update field specialty_id in doctors model.

Revision details for database migration.

Revision ID: 2cfa5572c62c
Revises: 01eb609ef020
Create Date: 2026-03-02 22:48:37.078811
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cfa5572c62c"
down_revision: str | None = "01eb609ef020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("doctors", "specialty_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("doctors", "specialty_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
